name: Stress testing problems with brute force solutions available
on: [push, pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - run: bash mine.sh


